import type { AppState } from "./relationship";

/**
 * Dados iniciais mockados — a interface nunca começa vazia.
 * Personagens, memórias, missões, metas, conversas e aspirações fictícios.
 */
export const seed: AppState = {
  coupleName: "Matheus & Luiza",
  saveTagline: "Um mundinho só nosso, em construção",
  currentChapter: {
    title: "Capítulo 1 — O começo de tudo",
    subtitle: "Duas cabeças curiosas começaram uma história que continua se escrevendo.",
  },
  saveWeather: { emoji: "🌤️", label: "Céu de tarde preguiçosa" },
  nowPlaying: { title: "You're My Best Friend", artist: "Queen", album: "A Night at the Opera" },
  featuredConversationId: "conv-1",

  characters: [
    {
      id: "char-1",
      name: "Matheus",
      image: "/avatar-matheus.jpg",
      emoji: "🌿",
      age: 32,
      tagline: "Curioso por tudo, mestre dos porquês",
      bio: "Constrói mapas mentais de tudo. Gosta de conectar ideias improváveis, entender como os sistemas funcionam e transformar curiosidade em projetos que dão certo (quase sempre).",
      mbti: "INTP",
      today: { emoji: "💡", text: "empolgado com uma nova ideia" },
      traits: ["INTP", "Curioso", "Criativo", "Observador", "Independente"],
      interests: [
        "Engenharia de Software",
        "Inteligência Artificial",
        "Design de Futuros",
        "Sistemas Complexos",
        "Economia",
        "Filosofia",
        "História",
        "Música",
      ],
      likes: [
        "Cafés tranquilos",
        "Dias frios",
        "Museus",
        "Livrarias",
        "Sushi",
        "Poke",
        "Trilhas leves",
        "Beatles",
        "Queen",
        "The Smiths",
        "Plantas",
        "Vinil",
        "Escape Rooms",
      ],
      quirks: [
        "Explica a origem das palavras sem perceber.",
        "Conecta assuntos completamente diferentes.",
        "Faz diagramas por diversão.",
        "Transforma qualquer ideia em framework.",
        "Lê placas, mapas e infográficos por curiosidade.",
        "Sempre pergunta \"qual é o sistema por trás disso?\"",
        "Costuma enxergar tendências antes de aplicações.",
        "Guarda referências para projetos futuros.",
      ],
      affectionStyles: [
        "Toque e cócegas",
        "Conversas profundas",
        "Pequenos gestos de cuidado",
        "Criar projetos juntos",
        "Caminhadas sem pressa",
      ],
      energySources: [
        "Aprender algo novo",
        "Conversas longas",
        "Construir projetos",
        "Boa comida",
        "Caminhar",
        "Dias nublados",
        "Silêncio compartilhado",
        "Ensinar alguma coisa",
      ],
      energyDrains: [
        "Calor excessivo",
        "Lugares muito barulhentos",
        "Conversas superficiais por muito tempo",
        "Burocracia desnecessária",
        "Interrupções constantes",
        "Ambientes caóticos",
      ],
      aspirations: [
        "Construir a Atlas",
        "Escrever livros e ensaios",
        "Tornar Design de Futuros mais acessível",
        "Criar ferramentas que ampliem a inteligência humana",
        "Aprender continuamente",
        "Desenvolver uma carreira internacional",
        "Construir uma casa cheia de livros, plantas e música",
      ],
      inventory: [
        "📚 Livro",
        "🎸 Violão",
        "💻 Notebook",
        "🎧 Fone de ouvido",
        "🗺️ Caderno de ideias",
      ],
      soundtrack: ["The Beatles", "Queen", "The Who", "The Smiths", "Led Zeppelin", "Mac DeMarco"],
      characterQuote: "Existe um padrão escondido aqui. Só precisamos olhar pelo ângulo certo.",
    },
    {
      id: "char-2",
      name: "Luiza",
      image: "/avatar-luiza.jpg",
      emoji: "🌻",
      age: 23,
      tagline: "Encontra beleza nas pequenas coisas",
      bio: "Encontra beleza nas pequenas coisas. Guarda lembranças como quem coleciona pedaços de dias felizes e transforma momentos simples em histórias que valem a pena revisitar.",
      mbti: "INTP",
      today: { emoji: "🏺", text: "inspirada com cerâmica" },
      traits: [
        "INTP",
        "Criativa",
        "Independente",
        "Observadora",
        "Bem-humorada",
        "Sensível",
        "Espontânea",
        "Autêntica",
      ],
      interests: [
        "Fotografia",
        "Cerâmica",
        "Cinema",
        "Música",
        "Caminhadas",
        "Cafés",
        "Livrarias",
        "Natureza",
        "Gatos",
        "Psicologia",
      ],
      likes: [
        "Dias chuvosos",
        "Café coado",
        "Girassóis",
        "The Smiths",
        "Queen",
        "Oasis",
        "Sushi",
        "Trilhas",
        "Feiras de rua",
        "Livrarias antigas",
        "Museus",
        "Janelas abertas quando está frio",
      ],
      quirks: [
        "Conversa com plantas como se fossem pessoas.",
        "Guarda ingressos, bilhetes e pequenas lembranças.",
        "Encontra detalhes que quase ninguém percebe.",
        "Tem um humor seco e inteligente.",
        "Faz piadas inesperadas no momento certo.",
        "Sorri quando começa a chover.",
        "Costuma transformar lugares comuns em lugares especiais.",
      ],
      affectionStyles: [
        "Tempo de qualidade",
        "Conversas sinceras",
        "Abraços demorados",
        "Bilhetinhos",
        "Pequenos gestos espontâneos",
        "Compartilhar músicas",
      ],
      energySources: [
        "Dias tranquilos",
        "Ouvir música",
        "Fotografar",
        "Estar perto de quem ama",
        "Descobrir um café novo",
        "Caminhar sem destino",
        "Criar alguma coisa com as mãos",
        "Longas conversas",
      ],
      energyDrains: [
        "Ambientes muito barulhentos",
        "Pressão constante",
        "Conflitos prolongados",
        "Pessoas invasivas",
        "Lugares excessivamente cheios",
        "Sentir que não pode ser ela mesma",
      ],
      aspirations: [
        "Ter um ateliê para criar.",
        "Fotografar lugares especiais.",
        "Conhecer novos países.",
        "Construir uma casa acolhedora.",
        "Viver uma rotina mais leve.",
        "Continuar descobrindo novas formas de expressão.",
      ],
      skills: [
        "Escutar com atenção",
        "Encontrar beleza em pequenos detalhes",
        "Criatividade",
        "Sensibilidade estética",
        "Humor espontâneo",
        "Criar ambientes acolhedores",
      ],
      worldview: [
        "Pequenos momentos costumam valer mais do que grandes eventos.",
        "Bons relacionamentos são construídos no cotidiano.",
        "Lugares carregam memórias.",
        "A autenticidade importa mais do que seguir expectativas.",
        "A vida fica melhor quando existe espaço para curiosidade e afeto.",
      ],
      inventory: [
        "📷 Câmera",
        "🌻 Girassol",
        "☕ Caneca de café",
        "🎧 Fones",
        "📚 Livro",
        "🎫 Ingresso de show",
        "🪴 Planta",
        "🎨 Bloco de desenho",
      ],
      soundtrack: ["The Smiths", "Queen", "Oasis"],
      characterQuote: "A melhor parte dos dias costuma estar escondida nos detalhes.",
    },
  ],

  memories: [
    {
      id: "mem-1",
      title: "O dia em que a gente se conheceu",
      description: "Duas cabeças curiosas começaram uma conversa que parecia não querer acabar.",
      date: "2026-04-20",
      emoji: "✨",
      category: "Capítulo 1 — O começo de tudo",
      tags: ["primeiroEncontro", "começo", "curiosidade"],
    },
    {
      id: "mem-2",
      title: "Primeiro encontro no Mug",
      description: "Uma salada compartilhada, banoffee e uma conversa que passou muito mais rápido do que deveria.",
      date: "2026-04-25",
      emoji: "☕",
      category: "Capítulo 1 — O começo de tudo",
      tags: ["Mug", "primeiroEncontro", "banoffee"],
    },
    {
      id: "mem-3",
      title: "Primeira vez em casa",
      description: "Quando o mundo ficou um pouco menor e mais confortável.",
      date: "2026-04-30",
      emoji: "🏡",
      category: "Capítulo 1 — O começo de tudo",
      tags: ["intimidade", "novoCapítulo"],
    },
    {
      id: "mem-4",
      title: "Café no MAC + caminhada no Ibirapuera",
      description: "Um daqueles dias em que caminhar parecia mais importante do que chegar.",
      date: "2026-05-09",
      emoji: "🌳",
      category: "Capítulo 1 — O começo de tudo",
      tags: ["MAC", "Ibirapuera", "passeio"],
    },
    {
      id: "mem-5",
      title: "Começamos a treinar juntos",
      description: "A academia deixou de ser apenas treino e virou mais um lugar para dividir a rotina.",
      date: "2026-05-16",
      emoji: "🏋️",
      category: "Capítulo 2 — Criando nossos rituais",
      tags: ["SmartFit", "rotina"],
    },
    {
      id: "mem-6",
      title: "Queen para cantar junto",
      description: "O primeiro show. Descobrimos que cantar desafinado junto também conta como talento.",
      date: "2026-05-23",
      emoji: "👑",
      category: "Capítulo 2 — Criando nossos rituais",
      tags: ["Queen", "show"],
    },
    {
      id: "mem-7",
      title: "Descobrindo o Codex",
      description: "Ela resolveu brincar com programação depois de conhecer o Codex. Foi divertido ver a curiosidade vencer a timidez.",
      date: "2026-05-30",
      emoji: "🎮",
      category: "Capítulo 2 — Criando nossos rituais",
      tags: ["IA", "Codex", "descobertas"],
    },
    {
      id: "mem-8",
      title: "Nosso restaurante favorito",
      description: "Sushi virou praticamente uma tradição.",
      date: "2026-06-06",
      emoji: "🍣",
      category: "Capítulo 2 — Criando nossos rituais",
      tags: ["sushi", "ritual"],
    },
    {
      id: "mem-9",
      title: "Feira do Livro",
      description: "Entre livros, caminhadas e boas conversas.",
      date: "2026-06-13",
      emoji: "📚",
      category: "Capítulo 3 — Expandindo nosso mundo",
      tags: ["livros", "passeio"],
    },
    {
      id: "mem-10",
      title: "Escape Room",
      description: "Descobrimos que resolver enigmas juntos também faz parte do relacionamento.",
      date: "2026-06-20",
      emoji: "🧩",
      category: "Capítulo 3 — Expandindo nosso mundo",
      tags: ["escapeRoom", "aventura"],
    },
    {
      id: "mem-11",
      title: "Violão em casa",
      description: "Queen, The Smiths e algumas notas desafinadas.",
      date: "2026-06-27",
      emoji: "🎸",
      category: "Capítulo 3 — Expandindo nosso mundo",
      tags: ["música", "casa"],
    },
    {
      id: "mem-12",
      title: "Bolo de cenoura + salada",
      description: "Cada um levou um pedaço do próprio mundo para a mesa.",
      date: "2026-07-04",
      emoji: "🍰",
      category: "Capítulo 3 — Expandindo nosso mundo",
      tags: ["cozinhar", "cotidiano"],
    },
    {
      id: "mem-13",
      title: "Girassóis",
      description: "Aprendi que algumas flores carregam significados maiores do que parecem.",
      date: "2026-07-11",
      emoji: "🌻",
      category: "Capítulo 3 — Expandindo nosso mundo",
      tags: ["flores", "carinho"],
    },
    {
      id: "mem-14",
      title: "A ligação depois da viagem",
      description: "Depois de um dia difícil, ela quis ligar. Não resolvemos tudo naquela noite, mas decidimos continuar conversando.",
      date: "2026-07-12",
      emoji: "📞",
      category: "Capítulo 4 — Aprendendo a atravessar tempestades",
      tags: ["reconciliação", "confiança"],
    },
    {
      id: "mem-15",
      title: "Narrando o voo",
      description: "Do embarque ao táxi. Pequenos detalhes que só contamos para quem faz parte da nossa rotina.",
      date: "2026-07-13",
      emoji: "✈️",
      category: "Capítulo 4 — Aprendendo a atravessar tempestades",
      tags: ["cotidiano", "proximidade"],
    },
    {
      id: "mem-16",
      title: "O sonho",
      description: "Alguns sonhos dizem mais sobre nossos medos e esperanças do que sobre a própria noite.",
      date: "2026-07-14",
      emoji: "💭",
      category: "Capítulo 4 — Aprendendo a atravessar tempestades",
      tags: ["sonhos", "reflexão"],
    },
    {
      id: "mem-17",
      title: "Primeiro dia de chuva juntos",
      description: "Descobri que algumas pessoas realmente ficam mais felizes quando começa a chover.",
      date: "2026-07-15",
      emoji: "☔",
      category: "Capítulo 5 — Nosso mundo",
      tags: ["chuva"],
    },
    {
      id: "mem-18",
      title: "Café sem pressa",
      description: "Às vezes o encontro não precisava ter destino.",
      date: "2026-07-16",
      emoji: "☕",
      category: "Capítulo 5 — Nosso mundo",
      tags: ["cafés"],
    },
    {
      id: "mem-19",
      title: "Playlist compartilhada",
      description: "Cada música nova passou a carregar um pedaço da nossa história.",
      date: "2026-07-17",
      emoji: "🎶",
      category: "Capítulo 5 — Nosso mundo",
      tags: ["playlist"],
    },
    {
      id: "mem-20",
      title: "Primeira foto favorita",
      description: "Aquela foto que sempre volta quando pensamos um no outro.",
      date: "2026-07-18",
      emoji: "📷",
      category: "Capítulo 5 — Nosso mundo",
      tags: ["memória"],
    },
  ],

  missions: [
    {
      id: "mis-1",
      title: "Piquenique ao pôr do sol",
      description: "Levar câmera analógica e a manta xadrez.",
      category: "encontro",
      status: "planned",
      date: "2026-07-26",
      steps: [
        { id: "s1", title: "Comprar frutas na feira", completed: true },
        { id: "s2", title: "Carregar a câmera", completed: false },
        { id: "s3", title: "Montar playlist do fim de tarde", completed: false },
      ],
    },
    {
      id: "mis-2",
      title: "Maratona de filmes cult",
      description: "Uma sexta por mês, cada um escolhe um filme surpresa.",
      category: "cotidiano",
      status: "idea",
    },
    {
      id: "mis-3",
      title: "Aula de cerâmica em dupla",
      category: "experiencia",
      status: "planned",
      date: "2026-08-09",
      steps: [
        { id: "s1", title: "Escolher o ateliê", completed: true },
        { id: "s2", title: "Reservar a data", completed: false },
      ],
    },
    {
      id: "mis-4",
      title: "Fim de semana na praia",
      description: "Aquele descanso sem despertador.",
      category: "viagem",
      status: "completed",
      date: "2026-05-18",
    },
    {
      id: "mis-5",
      title: "Café escondido no centro",
      category: "passeio",
      status: "archived",
    },
    {
      id: "mis-6",
      title: "Show do The Smiths",
      description: "Uma noite para cantar junto e guardar mais uma memória na trilha sonora da gente.",
      category: "experiencia",
      status: "planned",
      date: "2026-08-08",
    },
  ],

  goals: [
    {
      id: "goal-1",
      title: "Cozinhar um prato novo por semana",
      horizon: "short",
      progressType: "percentage",
      progress: 60,
      description: "Rodízio de receitas do mundo, um continente por vez.",
    },
    {
      id: "goal-2",
      title: "Planejar a viagem dos sonhos",
      horizon: "medium",
      progressType: "checklist",
      steps: [
        { id: "g2s1", title: "Escolher o destino", completed: true },
        { id: "g2s2", title: "Definir orçamento", completed: true },
        { id: "g2s3", title: "Reservar passagens", completed: false },
        { id: "g2s4", title: "Montar roteiro leve", completed: false },
      ],
    },
    {
      id: "goal-3",
      title: "Construir uma casa cheia de plantas e histórias",
      horizon: "long",
      progressType: "narrative",
      description:
        "Um lugar com horta, muitos livros e espaço para receber quem a gente ama.",
    },
    {
      id: "goal-4",
      title: "Treinar ao menos 3x na semana",
      horizon: "short",
      progressType: "checklist",
      steps: [
        { id: "g4s1", title: "Treino 1", completed: false },
        { id: "g4s2", title: "Treino 2", completed: false },
        { id: "g4s3", title: "Treino 3", completed: false },
      ],
      description: "Criar um ritmo sustentável de movimento juntos.",
    },
    {
      id: "goal-5",
      title: "Comer menos doces",
      horizon: "short",
      progressType: "percentage",
      progress: 0,
      description: "Diminuir aos poucos, sem transformar cuidado em cobrança.",
    },
    {
      id: "goal-6",
      title: "Planejar uma viagem em novembro",
      horizon: "medium",
      progressType: "checklist",
      steps: [
        { id: "g6s1", title: "Escolher o destino", completed: false },
        { id: "g6s2", title: "Definir orçamento", completed: false },
        { id: "g6s3", title: "Montar o roteiro", completed: false },
      ],
    },
  ],

  conversations: [
    {
      id: "conv-1",
      title: "Como queremos passar as festas de fim de ano",
      context: "Equilibrar as duas famílias sem correria.",
      topics: ["Dividir as datas", "Criar uma tradição nossa", "Viajar ou ficar?"],
      sensitivity: "meaningful",
      status: "ready",
    },
    {
      id: "conv-2",
      title: "Nossos ritmos de energia social",
      context: "Entender quando cada um precisa de recolhimento.",
      topics: ["Sinais de cansaço", "Combinar pausas", "Planos que respeitam os dois"],
      sensitivity: "delicate",
      status: "horizon",
    },
    {
      id: "conv-3",
      title: "Playlist colaborativa da casa",
      topics: ["Regras bobas", "Música proibida (brincadeira)"],
      sensitivity: "light",
      status: "discussed",
    },
  ],

  aspirations: [
    {
      id: "asp-1",
      title: "Conhecer novos lugares todo ano",
      description: "Nem que seja uma cidade pequena aqui perto.",
      emoji: "🧭",
    },
    {
      id: "asp-2",
      title: "Criar rituais só nossos",
      description: "Do café de domingo ao cinema da quarta.",
      emoji: "🕯️",
    },
    {
      id: "asp-3",
      title: "Aprender algo em dupla",
      description: "Um idioma, um instrumento, uma dança.",
      emoji: "🎨",
    },
  ],
};

export function cloneSeed(): AppState {
  return structuredClone
    ? structuredClone(seed)
    : JSON.parse(JSON.stringify(seed));
}
